version: '3'
services:
  nacos:
    container_name: nacos
    # image: nacos/nacos-server:latest
    image: zhusaidong/nacos-server-m1:2.0.3
    platform: linux/arm64
    # platform: linux/amd64
    restart: always
    ports:
      - "8848:8848"
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=256m

